[package]
name = "reql"
description = "RethinkDB driver"
version = "0.0.4"
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-rethinkdb/reql"
documentation = "https://docs.rs/reql"
readme = "README.md"
keywords = ["database", "rethinkdb", "reql", "driver"]
authors = ["rushmorem <rushmore@webenchanter.com>"]

build = "build.rs"

[dependencies]
ql2 = "1.0"
protobuf = "1.0"
r2d2 = "0.7"
byteorder = "0.5"
bufstream = "0.1"
futures = "0.1"
tokio-core = "0.1"
slog = "1.0"
slog-term = "1.0"
serde = "0.8"
serde_json = "0.8"
lazy_static = "0.2"
#uuid = { version = "0.3", features = ["v4", "use_std"] }
scram = "0.1"
quick-error = "1.1"
parking_lot = "0.3"
rayon = "0.4"

[build-dependencies]
skeptic = "0.6"
serde_codegen = "0.8"

[dev-dependencies]
skeptic = "0.6"
