[package]
name = "reql"
description = "A native ReQL driver"
version = "0.0.20"
license = "MIT/Apache-2.0"
repository = "https://github.com/RebirthDB/rebirthdb-rs"
documentation = "https://docs.rs/reql"
readme = "README.md"
keywords = ["database", "rethinkdb", "rebirthdb", "reql", "driver"]
categories = ["database"]
authors = ["rushmorem <rushmore@webenchanter.com>"]
build = "build/main.rs"

[badges]
travis-ci = { repository = "RebirthDB/rebirthdb-rs" }

[features]
tls = ["native-tls"]

[dependencies]
protobuf = ">= 1.4, < 1.6"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
ql2 = "1.1"
derive-error = "0.0.4"
lazy_static = "1.0"
serde_derive = "1.0"
r2d2 = "0.8"
byteorder = "1.0"
bufstream = "0.1"
scram-tmp = "0.4"
futures = "0.1"
parking_lot = "0.5"
indexmap = "1.0"
reql-types = { version = "0.0.3", path = "./types" }
uuid = { version = "0.6", features = ["v4", "serde"] }
native-tls = { version = "0.1", optional = true }

[build-dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
nom = "4.0"
