[package]
name = "reql"
description = "A native ReQL driver"
version = "0.0.24-alpha.0"
license = "MIT/Apache-2.0"
repository = "https://github.com/RethinkDB/rethinkdb-rs"
documentation = "https://docs.rs/reql"
readme = "README.md"
keywords = ["database", "rethinkdb", "rethinkdb", "reql", "driver"]
categories = ["database"]
authors = ["rushmorem <rushmore@webenchanter.com>"]
build = "build/main.rs"
edition = "2018"

[badges]
travis-ci = { repository = "RethinkDB/rethinkdb-rs" }

[features]
tls = ["native-tls"]

[dependencies]
protobuf = ">= 1.4, < 1.6"
log = "0.4"
serde = "1"
serde_json = "1"
ql2 = "1.1"
derive-error = "0.0.4"
lazy_static = "1"
serde_derive = "1"
r2d2 = "0.8"
byteorder = "1"
bufstream = "0.1"
scram = "0.4"
futures = "0.1"
parking_lot = "0.6"
indexmap = "1"
reql-types = { version = "0.0.4", path = "./types" }
uuid = { version = "0.7", features = ["v4", "serde"] }
native-tls = { version = "0.2", optional = true }

[build-dependencies]
serde = "1"
serde_derive = "1"
serde_yaml = "0.8"
nom = "4.0"
