[package]
name = "reql"
description = "A native ReQL driver"
version = "0.1.0-alpha.0"
license = "MIT/Apache-2.0"
repository = "https://github.com/rethinkdb/rethinkdb-rs"
documentation = "https://docs.rs/reql"
readme = "README.md"
keywords = ["database", "rethinkdb", "rethinkdb", "reql", "driver"]
categories = ["database"]
authors = ["rushmorem <rushmore@webenchanter.com>"]
edition = "2018"

[badges]
travis-ci = { repository = "rethinkdb/rethinkdb-rs" }

[dependencies]
log = "0.4.6"
serde = { version = "1.0.82", features = ["derive"] }
serde_json = "1.0.33"
scram = "0.4.0"
futures-preview = "0.3.0-alpha.10"
reql-types = { version = "0.0.4", path = "./types" }
uuid = { version = "0.7.1", features = ["v4", "serde"] }
romio = "0.3.0-alpha.1"
atomic-counter = "1.0.1"
