[package]
name = "reql"
description = "A native RethinkDB driver"
version = "0.0.6-alpha1"
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-rethinkdb/reql"
documentation = "https://docs.rs/reql/*/reql/commands/"
readme = "README.md"
keywords = ["database", "rethinkdb", "reql", "driver"]
categories = ["database"]
authors = ["rushmorem <rushmore@webenchanter.com>"]

[badges]
travis-ci = { repository = "rust-rethinkdb/reql" }

[dependencies]
ql2 = "1.1"
protobuf = "1.1"
slog = "1.5"
serde_json = "0.9"
derive-error = "0.0.3"
reql-derive = { path = "./reql-derive" }
