[package]
name = "reql"
description = "A native RethinkDB driver"
version = "0.0.6-alpha10"
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-rethinkdb/reql"
documentation = "https://docs.rs/reql"
readme = "README.md"
keywords = ["database", "rethinkdb", "reql", "driver"]
categories = ["database"]
authors = ["rushmorem <rushmore@webenchanter.com>"]
build = "build/main.rs"

[badges]
travis-ci = { repository = "rust-rethinkdb/reql" }
appveyor = { repository = "rust-rethinkdb/reql" }

[features]
default = ["with-io"]
with-io = ["lazy_static", "serde_derive", "r2d2", "byteorder",
	"bufstream", "scram", "tokio-core", "futures",
	"parking_lot", "uuid", "ordermap"]

[dependencies]
protobuf = "1.2"
slog = "1.5"
serde = "1.0"
serde_json = "1.0"
ql2 = "1.1"
derive-error = "0.0.3"
proc-macro-hack = "0.3"
reql-derive = { version = "0.0.6", path = "./derive" }
reql-types = { version = "0.0.1", path = "./types" }

# IO dependencies
lazy_static = { version = "0.2", optional = true }
serde_derive = { version = "1.0", optional = true }
r2d2 = { version = "0.7", optional = true }
byteorder = { version = "1.0", optional = true }
bufstream = { version = "0.1", optional = true }
scram = { version = "0.1", optional = true }
tokio-core = { version = "0.1", optional = true }
futures = { version = "0.1", optional = true }
parking_lot = { version = "0.4", optional = true }
uuid = { version = "0.5", features = ["use_std", "v4", "serde"], optional = true }
ordermap = { version = "0.2", optional = true }

[dev-dependencies]
slog-term = "1.5"

[build-dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
nom = "2.1"
