[package]
name = "reql"
description = "Common traits and errors for RethinkDB drivers"
version = "0.0.4"
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-rethinkdb/reql"
documentation = "http://rust-rethinkdb.github.io/reql/0.1.x/reql"
readme = "README.md"
keywords = ["database", "rethinkdb", "reql"]
authors = ["rushmorem <rushmore@webenchanter.com>"]

[dependencies]
r2d2 = "0.7.0"
quick-error = "1.1.0"
serde_json = "0.8.2"
