[package]
name = "reql-derive"
description = "Derive macro used by the reql crate"
version = "0.0.6-alpha3"
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-rethinkdb/reql"
authors = ["rushmorem <rushmore@webenchanter.com>"]

[dependencies]
syn = "0.11"
quote = "0.3"
case = "0.1"

[lib]
proc-macro = true
