[package]
name = "reql-derive"
description = "An implementation of the args macro used by the reql crate"
version = "0.0.6"
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-rethinkdb/reql"
authors = ["rushmorem <rushmore@webenchanter.com>"]

[dependencies]
syn = "0.11"
quote = "0.3"
proc-macro-hack = "0.3"

[lib]
proc-macro = true
