[package]
name = "reql-types"
description = "Some useful types to use along with the reql crate"
version = "0.0.4"
license = "MIT/Apache-2.0"
repository = "https://github.com/RebirthDB/rebirthdb-rs"
documentation = "https://docs.rs/reql-types"
authors = ["rushmorem <rushmore@webenchanter.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chrono = "0.4"
uuid = { version = "0.6", features = ["v4", "serde"] }
